[build]
  command = "npm run build"
  publish = "build"
  environment = { 
    NODE_VERSION = "18.3.1", # Ajusta la versión de Node.js si es necesario
    NPM_FLAGS = "--legacy-peer-deps"
  }

[build.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-react"  # Plugin para manejar proyectos React (opcional)

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200